### ISSUE TITLE
cde_id and ontology_id to new standardsMappings and relatedConcepts

### ISSUE THREAD

**Issue by mbkranz** [HEAL/heal-metadata-schemas#23]
- [x] Add to definitions.yaml (and comment out cde_id/ontology_id -- keep to allow for context for now)
- [x] Run build.py for new "minimal" schemas
- [x] Add controlled vocabularies to definitions.yaml
- [x] Beef up examples/descriptions (#25)
- [x] Submit PR

**Comment by mbkranz** [comment]
- standardsMappings: type, label, url, source, id
- relatedConcepts: type, label, url, source, id (or only url?)

**Comment by gaurav** [comment]
I like having source, id and url for relatedConcepts -- it would mean more work in generating a list of sources that could be used here, but there might be people who want to use e.g. the NCI Thesaurus concepts might prefer to use `NCIT:C12468` instead of the official URL for this concept, which is https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C12468 (and not very readable).

**Comment by mbkranz** [comment]
Make label required within standardsMapping

**Comment by mbkranz** [comment]
PR #29  was merged
